// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock_Analyzer_Repository;

#nullable disable

namespace Stock_Analyzer_Repository.Migrations
{
    [DbContext(typeof(StockAnalyzerContext))]
    [Migration("20231028164303_Updated Filter table(added series field)")]
    partial class UpdatedFiltertableaddedseriesfield
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.BhavCopyInfoDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPrice")
                        .HasColumnType("float");

                    b.Property<double>("ClosePrice")
                        .HasColumnType("float");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DeliveryPercentage")
                        .HasColumnType("float");

                    b.Property<double>("DeliveryQty")
                        .HasColumnType("float");

                    b.Property<double>("HighPrice")
                        .HasColumnType("float");

                    b.Property<double>("LastPrice")
                        .HasColumnType("float");

                    b.Property<double>("LowPrice")
                        .HasColumnType("float");

                    b.Property<double>("NoOfTrades")
                        .HasColumnType("float");

                    b.Property<double>("OpenPrice")
                        .HasColumnType("float");

                    b.Property<double>("PreviousClose")
                        .HasColumnType("float");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TtlTrdQnty")
                        .HasColumnType("float");

                    b.Property<double>("TurnOverLacs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BhavCopyInfo");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.BulkDealDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAction")
                        .HasColumnType("int");

                    b.Property<double>("TradePrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("BulkDeal");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.ClientDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.CompanyDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterCriteriaDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogicalOperator")
                        .HasColumnType("int");

                    b.Property<int>("PeriodType")
                        .HasColumnType("int");

                    b.Property<int>("PeriodValue")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("filterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("filterId");

                    b.ToTable("FilterCriteria");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilterName")
                        .IsUnique();

                    b.ToTable("Filter");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterResultDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FilterCriteriaId");

                    b.ToTable("FilterResult");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.BhavCopyInfoDataModel", b =>
                {
                    b.HasOne("Stock_Analyzer_Repository.DataModels.CompanyDataModel", "Company")
                        .WithMany("BhavCopyInfos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.BulkDealDataModel", b =>
                {
                    b.HasOne("Stock_Analyzer_Repository.DataModels.ClientDataModel", "Client")
                        .WithMany("Deals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stock_Analyzer_Repository.DataModels.CompanyDataModel", "Company")
                        .WithMany("BulkDeals")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterCriteriaDataModel", b =>
                {
                    b.HasOne("Stock_Analyzer_Repository.DataModels.Filter.FilterDataModel", "FilterDataModel")
                        .WithMany("Criterias")
                        .HasForeignKey("filterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterDataModel");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterResultDataModel", b =>
                {
                    b.HasOne("Stock_Analyzer_Repository.DataModels.CompanyDataModel", "CompanyDataModel")
                        .WithMany("FilterResults")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stock_Analyzer_Repository.DataModels.Filter.FilterCriteriaDataModel", "FilterCriteriaDataModel")
                        .WithMany("FilterResults")
                        .HasForeignKey("FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyDataModel");

                    b.Navigation("FilterCriteriaDataModel");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.ClientDataModel", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.CompanyDataModel", b =>
                {
                    b.Navigation("BhavCopyInfos");

                    b.Navigation("BulkDeals");

                    b.Navigation("FilterResults");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterCriteriaDataModel", b =>
                {
                    b.Navigation("FilterResults");
                });

            modelBuilder.Entity("Stock_Analyzer_Repository.DataModels.Filter.FilterDataModel", b =>
                {
                    b.Navigation("Criterias");
                });
#pragma warning restore 612, 618
        }
    }
}
